-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 16:36:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cbd19a
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cbd19a` ;

-- -----------------------------------------------------
-- Schema cbd19a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cbd19a` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `cbd19a` ;

-- -----------------------------------------------------
-- Table `cbd19a`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbd19a`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cbd19a`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) UNSIGNED NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(200) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) UNSIGNED NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cbd19a`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbd19a`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cbd19a`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT UNSIGNED NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(200) NOT NULL,
  `cus_balance` DECIMAL(8,2) UNSIGNED NOT NULL,
  `cus_total_sales` DECIMAL(8,2) UNSIGNED NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cbd19a`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cbd19a`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cbd19a`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pet_age` TINYINT UNSIGNED NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_petstore_idx` (`pst_id` ASC) VISIBLE,
  INDEX `fk_pet_customer1_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_petstore`
    FOREIGN KEY (`pst_id`)
    REFERENCES `cbd19a`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_customer1`
    FOREIGN KEY (`cus_id`)
    REFERENCES `cbd19a`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cbd19a`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `cbd19a`;
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Wildwood Exotic Pets', '213 Bridgewater Street', 'Tallahassee ', 'FL', 32304, 8134357395, 'wildwoodexoticpets@aol.com', 'www.wildwoodexoticpets.com', 5000, 'notes1');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Tails Pets\n', '2112 Heirloom Avenue', 'Riverview', 'FL', 33511, 8134057873, 'happytailspets@aol.com', 'www.happytailspets.com', 4400, 'notes2');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets Unleashed', '918 Lawn Lane', 'Valrico', 'FL', 33527, 8130198927, 'petsunleashed@aol.com', 'www.petsunleashed.com', 7500, 'notes3');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Paws\n', '527 Liberty Lane', 'Tamps', 'FL', 33601, 8136675889, 'happypaws@aol.com', 'www.happypaws.com', 8000, 'notes4');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'The Puppy Patch', '1092 Grace Street', 'Orlando', 'FL', 32789, 8131029443, 'puppypatch@aol.com', 'www.puppypatch.com', 3200, 'notes5');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Sweet Tweets Pet Store', '091 Parkside Avenue', 'Miami', 'FL', 33101, 8132223419, 'sweettweetspetstore@aol.com', 'www.sweettweetspetstore.com', 5500, 'notes6');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'The Pet Stop', '433 Farmer Route', 'Sarasota', 'FL', 34230, 8135048279, 'petstore@aol.com', 'www.petstore.com', 6500, 'notes7');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Cuddle Love Pets', '828 Bard Street', 'Dade City', 'FL', 33525, 8133234053, 'cuddlelovepets@aol.com', 'www.cuddlelovepets.com', 4000, 'notes8');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Family Pets', '111 Crown Lane', 'Plant City', 'FL', 33566, 8132847509, 'furryfamiltpets@aol.com', 'www.furryfamiltpets.com', 5800, 'notes9');
INSERT INTO `cbd19a`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furballs Pet Shop', '921 Earl Avenue', 'Brandon', 'FL', 33508, 8134099988, 'furballspetshop@aol.com', 'www.furballspetshop.com', 7000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cbd19a`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `cbd19a`;
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Bob', 'Steven', '2733 Hind Row', 'Orlando', 'FL', 32234, 8135647898, 'BobSteven@aol.com', 55.50, 500.50, 'notes1');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'John', 'Brooks', '9323 Garnet Street', 'Tamps', 'FL', 33601, 8132341234, 'JohnBrooks@aol.com', 400.10, 800.00, 'notes2');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sam', 'Jackson', '782 Copper Way', 'Plant City', 'FL', 33566, 8132907834, 'SamJackson@aol.com', 25.00, 125.00, 'notes3');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Noah', 'Coleman', '3918 Vista Bouled', 'Riverview', 'FL', 33511, 8134019365, 'NoahColeman@aol.com', 19.40, 230.00, 'notes4');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Danny', 'Fleming', '234 Bath Row', 'Sarasota', 'FL', 34230, 8138711298, 'DannyFlemming@aol.com', 123.40, 754.30, 'notes5');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ben', 'Watson', '126 Colonel Avenue', 'Tallahassee ', 'FL', 32304, 8132894761, 'BenWatson@aol.com', 5432.30, 9000.20, 'notes6');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Cade', 'Ash', '245 Moonlight Lane', 'Miami', 'FL', 33101, 8139029384, 'CadeAsh@aol.com', 43.20, 100.20, 'notes7');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Carly', 'Moore', '3746 Temple Street', 'Dade City', 'FL', 33525, 8139828564, 'CarlyMoore@aol.com', 540.00, 780.30, 'notes8');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Sarah', 'Day', '9727 East Street', 'Brandon', 'FL', 33508, 8130938245, 'SarahDay@aol.com', 213.10, 322.90, 'notes9');
INSERT INTO `cbd19a`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Kate', 'Dixon', '7883 Clarity Way', 'Valrico', 'FL', 33527, 8135462341, 'KateDixon@aol.com', 76.80, 100.30, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cbd19a`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `cbd19a`;
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 10, 'French Bulldog', 'f', 70.00, 100.00, 52, 'tan', '2001-07-11', 'y', 'n', 'notes1');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, 4, 'Golden Retriever ', 'f', 120.00, 150.00, 78, 'tan', '2004-02-10', 'y', 'y', 'notes2');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, NULL, 'Corgi ', 'm', 50.00, 100.00, 104, 'tan', NULL, 'y', 'y', 'notes3');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, NULL, 'Poodle', 'f', 300.00, 400.00, 212, 'black', '2009-12-02', 'y', 'n', 'notes4');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 6, 'Pit Bull', 'm', 65.00, 125.00, 28, 'black', NULL, 'y', 'n', 'notes5');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, 8, 'English Bulldog', 'm', 75.00, 250.00, 2, 'tan', '2015-12-29', 'y', 'y', 'notes6');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, 2, 'Greyhound', 'm', 150.00, 300.00, 250, 'black', '2003-08-21', 'n', 'y', 'notes7');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, 3, 'Cocker Spaniel', 'f', 55.00, 100.00, 8, 'brown', '2008-06-19', 'n', 'n', 'notes8');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, NULL, 'Pomeranian', 'f', 60.00, 120.00, 80, 'tan', NULL, 'y', 'y', 'notes9');
INSERT INTO `cbd19a`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, NULL, 'Huskie', 'm', 145.00, 200.00, 208, 'black', '2006-01-15', 'y', 'y', 'notes10');

COMMIT;

